### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by matzeapps** [11notes/docker-sungrow#1]
Hi,

I am currently trying to integrate your Docker container. However, the login does not work and I always get the following error:

` Error: unknown error ''
sungrow  | Usage:
sungrow  |   GoSungrow api login [flags]
sungrow  |
sungrow  | Examples:
sungrow  |      GoSungrow api login
sungrow  |
sungrow  |
sungrow  | Flags: Use "GoSungrow help flags" for more info.
sungrow  |
sungrow  | Additional help topics:
sungrow  |
sungrow  | ERROR: unknown error ''
sungrow  | {"time":"2025-01-29T23:32:15.000Z","type":"ERR","msg":"could not login to SunGrow!"}
`

```yml
services:
  sungrow:
    container_name: "sungrow"
    image: "11notes/sungrow:3.0.7"
    environment:
      TZ: "Europe/Zurich"
      GOSUNGROW_USER: "myUser"
      GOSUNGROW_PASSWORD: "xxx"
      GOSUNGROW_HOST: "https://gateway.isolarcloud.eu"
      GOSUNGROW_APPKEY: "ANDROIDE13EC118BD7892FE7AB5A3F20"
      GOSUNGROW_MQTT_HOST: xx
      GOSUNGROW_MQTT_USER: user1
      GOSUNGROW_MQTT_PASSWORD: mypw
      GOSUNGROW_MQTT_PORT: 8883
      GOSUNGROW_MQTT_TOPIC: xx/solar/sungrow
    volumes:
      - /data/iSolarCloud/data:/sungrow/etc
    restart: no
```

If I run the login on my local Windows PC with the latest release (https://github.com/MickMake/GoSungrow/releases/tag/v3.0.7), then it works.

Is it still working for you?
